# Generated by Django 3.2 on 2024-10-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sayayin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivelfuerza', models.FloatField(max_length=50)),
                ('vecesresuciado', models.FloatField(max_length=3)),
                ('torneosgandos', models.FloatField(max_length=2)),
                ('edad', models.FloatField(max_length=3)),
                ('maestro', models.CharField(max_length=50)),
                ('transformacionmax', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
    ]
